{
  "hash": "b816386ec119d5bee02ec391f862ef56",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"A/B Testing a Call to Action\"\nsubtitle: \"Simulating Key Ideas from Classical Frequentist Statistics\"\nauthor: \"Ziyan (Freya) Zheng\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: true\n---\n\n\n\n## Introduction\n\nI run a personal website with a landing page where visitors can subscribe to my newsletter. The sign-up form is accompanied by a short line of text — a \"call to action\" (CTA) — designed to encourage visitors to subscribe. But does the exact wording of that line actually matter?\n\nTo find out, I designed a simple experiment comparing two CTAs:\n\n- **CTA A:** \"Sign up for our newsletter here!\"\n- **CTA B:** \"Stay up to date by signing up!\"\n\nRather than guessing which performs better, I ran an **A/B test**. Each visitor who arrives at the site is randomly assigned to see one of the two versions. At the end of the experiment, I compare the sign-up rates between the two groups. Because assignment is random, any difference in sign-up rates can be attributed to the wording rather than to differences in the visitors themselves.\n\nIn this post, I walk through the key statistical ideas behind this A/B test — from estimation and sampling variability to hypothesis testing and a common pitfall called \"peeking\" — all illustrated through simulation.\n\n---\n\n## The A/B Test as a Statistical Problem\n\nEach visitor either signs up or does not, so we can model each visitor's outcome as a draw from a **Bernoulli distribution** with parameter $\\pi$ — the probability of signing up. Because CTA wording may influence behavior, we allow this probability to differ by group: visitors who see CTA A have sign-up probability $\\pi_A$, and visitors who see CTA B have sign-up probability $\\pi_B$.\n\nThe quantity we care about is the **difference in sign-up rates**:\n$$\\theta = \\pi_A - \\pi_B$$\n\nIf $\\theta > 0$, CTA A is more effective; if $\\theta < 0$, CTA B wins; if $\\theta = 0$, the two CTAs perform equally.\n\nSince we cannot observe $\\pi_A$ and $\\pi_B$ directly, we estimate $\\theta$ from data using the difference in sample proportions:\n$$\\hat\\theta = \\bar{X}_A - \\bar{X}_B = \\hat\\pi_A - \\hat\\pi_B$$\n\nBecause each observation is either 0 or 1, the sample mean is just the proportion of visitors who signed up — so $\\bar{X}_A = \\hat\\pi_A$ and $\\bar{X}_B = \\hat\\pi_B$.\n\n---\n\n## Simulating Data\n\nIn a real experiment we would not know the true values of $\\pi_A$ and $\\pi_B$ — that's the whole point of running the test. But for this exercise we set them ourselves so that we can study how our estimator behaves when we know the truth.\n\nWe suppose:\n$$\\pi_A = 0.22, \\quad \\pi_B = 0.18, \\quad \\theta = \\pi_A - \\pi_B = 0.04$$\n\nCTA A leads to a 4 percentage point higher sign-up rate. We simulate 1,000 visitors assigned to each group (2,000 total).\n\n::: {#0554c2d4 .cell execution_count=2}\n``` {.python .cell-code}\npi_A = 0.22\npi_B = 0.18\nn = 1000\n\ndata_A = rng.binomial(1, pi_A, n)\ndata_B = rng.binomial(1, pi_B, n)\n\ntheta_hat = data_A.mean() - data_B.mean()\nprint(f\"True θ       = {pi_A - pi_B:.4f}\")\nprint(f\"Estimated θ̂  = {theta_hat:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTrue θ       = 0.0400\nEstimated θ̂  = 0.0250\n```\n:::\n:::\n\n\nOur sample estimate is close to the true value of 0.04 — reassuring, but not surprising given a sample of 1,000. The sections that follow explain *why* this estimate is trustworthy and *how certain* we should be about it.\n\n---\n\n## The Law of Large Numbers\n\nThe **Law of Large Numbers (LLN)** states that as the sample size grows, the sample mean converges to the population mean. In our context, this means $\\hat\\pi_A \\to \\pi_A$ and $\\hat\\pi_B \\to \\pi_B$ as $n \\to \\infty$, and therefore $\\hat\\theta \\to \\theta$. The LLN is what gives us confidence that our estimator will be close to the truth when the sample is large enough.\n\nTo demonstrate this, I compute the element-wise differences between the CTA A and CTA B draws to form a vector of 1,000 paired differences. The cumulative average of this vector — the running mean after 1 draw, 2 draws, ..., 1,000 draws — traces how quickly the estimate settles toward the true value of 0.04.\n\n::: {#3071e282 .cell execution_count=3}\n``` {.python .cell-code}\ndiffs = data_A - data_B\ncumulative_avg = np.cumsum(diffs) / np.arange(1, n + 1)\n\n# ±1.96 SE confidence band: SE of running mean shrinks as 1/sqrt(k)\n# SE of a single difference ~ sqrt(pi_A(1-pi_A) + pi_B(1-pi_B))\nse_single = np.sqrt(pi_A * (1 - pi_A) + pi_B * (1 - pi_B))\nk = np.arange(1, n + 1)\nband = 1.96 * se_single / np.sqrt(k)\n\nfig, ax = plt.subplots(figsize=(9, 4))\nax.fill_between(k, cumulative_avg - band, cumulative_avg + band,\n                color=\"#4C72B0\", alpha=0.15, label=\"95% confidence band\")\nax.plot(k, cumulative_avg, color=\"#4C72B0\", linewidth=1.4, label=\"Running mean of $\\\\hat{\\\\theta}$\")\nax.axhline(y=0.04, color=\"#DD4949\", linewidth=1.5, linestyle=\"--\", label=\"True $\\\\theta = 0.04$\")\nax.set_xlabel(\"Number of observations\", fontsize=12)\nax.set_ylabel(\"Cumulative average of differences\", fontsize=12)\nax.set_title(\"Law of Large Numbers: Running Estimate of $\\\\theta$\", fontsize=13, fontweight=\"bold\")\nax.legend(fontsize=11)\nax.set_xlim(1, n)\nax.set_ylim(-0.25, 0.35)\nax.grid(axis=\"y\", alpha=0.3)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-4-output-1.png){width=855 height=372}\n:::\n:::\n\n\nWith only a handful of observations the running average is noisy and erratic — and the shaded confidence band is wide, reflecting high uncertainty. As the sample grows, the band narrows at rate $1/\\sqrt{n}$, squeezing down around the estimate as it converges toward the true value of 0.04. This is the LLN and the shrinking-variance property working together: more data means a more precise estimate *and* a tighter band of plausible values.\n\n---\n\n## Bootstrap Standard Errors\n\nKnowing that $\\hat\\theta$ is close to $\\theta$ is only half the story. We also need to communicate our *uncertainty* — how much could $\\hat\\theta$ plausibly vary from one experiment to the next? This is where **standard errors** and **confidence intervals** come in.\n\n**The bootstrap** is a resampling technique that estimates variability without relying on a closed-form formula. The logic is simple: treat your observed data as a stand-in for the population, and simulate the act of re-running the experiment by drawing new samples (with replacement) from the data you already have. Each resample produces a new estimate $\\hat\\theta^*$, and the standard deviation of many such estimates approximates the standard error of $\\hat\\theta$.\n\n::: {#e956d8b2 .cell execution_count=4}\n``` {.python .cell-code}\nB = 1000\nboot_estimates = np.empty(B)\n\nfor b in range(B):\n    resample_A = rng.choice(data_A, size=n, replace=True)\n    resample_B = rng.choice(data_B, size=n, replace=True)\n    boot_estimates[b] = resample_A.mean() - resample_B.mean()\n\nse_boot = boot_estimates.std()\n\n# Analytical SE\npi_hat_A = data_A.mean()\npi_hat_B = data_B.mean()\nse_analytical = np.sqrt(pi_hat_A * (1 - pi_hat_A) / n + pi_hat_B * (1 - pi_hat_B) / n)\n\nci_lower = theta_hat - 1.96 * se_boot\nci_upper = theta_hat + 1.96 * se_boot\n\nresults = pd.DataFrame({\n    \"Method\": [\"Bootstrap\", \"Analytical\"],\n    \"Standard Error\": [f\"{se_boot:.5f}\", f\"{se_analytical:.5f}\"]\n})\nprint(results.to_string(index=False))\nprint(f\"\\n95% Bootstrap CI for θ: [{ci_lower:.4f}, {ci_upper:.4f}]\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Method Standard Error\n Bootstrap        0.01859\nAnalytical        0.01825\n\n95% Bootstrap CI for θ: [-0.0114, 0.0614]\n```\n:::\n:::\n\n\nThe bootstrapped and analytical standard errors are nearly identical — a reassuring sign that both approaches capture the same underlying variability. The 95% confidence interval for $\\theta$ does not include zero, suggesting that CTA A's higher sign-up rate is unlikely to be pure chance. We are 95% confident the true difference lies somewhere within that range.\n\n---\n\n## The Central Limit Theorem\n\nThe **Central Limit Theorem (CLT)** tells us that regardless of the shape of the underlying distribution, the sampling distribution of the sample mean becomes approximately Normal as the sample size grows. Since $\\hat\\theta = \\bar{X}_A - \\bar{X}_B$ is a difference of sample means, the CLT applies here too: for large enough $n$, the distribution of $\\hat\\theta$ is approximately $N(\\theta, \\text{SE}^2)$.\n\nOur individual observations are Bernoulli — a decidedly non-Normal distribution with only two possible values. Yet with enough data, the estimator based on those outcomes should look Normal. Let's see this in action.\n\nFor each of four sample sizes $n \\in \\{25, 50, 100, 500\\}$, I simulate 1,000 experiments and compute $\\hat\\theta$ in each. The four resulting histograms show how the sampling distribution evolves with $n$.\n\n::: {#4e1c2623 .cell execution_count=5}\n``` {.python .cell-code}\nsample_sizes = [25, 50, 100, 500]\nfig, axes = plt.subplots(2, 2, figsize=(10, 7))\naxes = axes.flatten()\nxlim = (-0.30, 0.35)\n\nfor i, size in enumerate(sample_sizes):\n    estimates = np.array([\n        rng.binomial(1, pi_A, size).mean() - rng.binomial(1, pi_B, size).mean()\n        for _ in range(1000)\n    ])\n    ax = axes[i]\n    ax.hist(estimates, bins=30, color=\"#4C72B0\", edgecolor=\"white\", alpha=0.85, density=True)\n    ax.axvline(x=0.04, color=\"#DD4949\", linestyle=\"--\", linewidth=1.5, label=\"True θ = 0.04\")\n\n    mu, sigma = estimates.mean(), estimates.std()\n    x = np.linspace(xlim[0], xlim[1], 200)\n    ax.plot(x, stats.norm.pdf(x, mu, sigma), color=\"#2ca02c\", linewidth=1.8, label=\"Normal fit\")\n\n    ax.set_xlim(xlim)\n    ax.set_title(f\"n = {size}\", fontsize=12, fontweight=\"bold\")\n    ax.set_xlabel(\"$\\\\hat{\\\\theta}$\", fontsize=11)\n    ax.set_ylabel(\"Density\", fontsize=10)\n    if i == 0:\n        ax.legend(fontsize=9)\n\nfig.suptitle(\"Sampling Distribution of $\\\\hat{\\\\theta}$ at Different Sample Sizes\\n(CLT Demonstration)\",\n             fontsize=13, fontweight=\"bold\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-6-output-1.png){width=949 height=661}\n:::\n:::\n\n\nAt $n = 25$ the histogram looks rough and slightly asymmetric — with so few observations per group, the estimator hasn't fully shed its Bernoulli origins. By $n = 100$ the shape is clearly bell-shaped, and by $n = 500$ the sampling distribution closely matches the overlaid Normal curve. This is the CLT in action: even though individual outcomes are binary (0 or 1), the *estimator* converges to a Normal distribution as we collect more data. This Normal approximation is what enables us to perform hypothesis tests and construct confidence intervals using familiar formulas.\n\n---\n\n## Hypothesis Testing\n\nNow that we know $\\hat\\theta$ is approximately Normally distributed for large samples, we can use this result to perform a **formal hypothesis test**.\n\nWe frame the question as a null hypothesis test:\n$$H_0: \\theta = 0 \\quad \\text{(the two CTAs perform equally)}$$\n$$H_1: \\theta \\neq 0 \\quad \\text{(the CTAs differ in effectiveness)}$$\n\nThe goal is to assess whether the data provide enough evidence to reject $H_0$. To do this, we compute a **test statistic** by standardizing $\\hat\\theta$:\n$$z = \\frac{\\hat\\theta - 0}{\\text{SE}(\\hat\\theta)}$$\n\nThe logic has three steps:\n\n1. By the CLT, $\\hat\\theta$ is approximately Normal for large samples. Under $H_0$, its mean is 0.\n2. Dividing a Normal random variable by its standard deviation yields a standard Normal $N(0,1)$. So under $H_0$, $z \\;\\dot\\sim\\; N(0,1)$.\n3. Because we know the distribution of $z$ under the null, we can calculate the probability of seeing a value as extreme as ours — the **p-value** — and use it to decide whether to reject $H_0$.\n\n**A note on \"t-test\" terminology:** This procedure is often called a two-sample t-test. The classical t-distribution arises when data are drawn from a Normal population and the variance must be estimated — the ratio then follows an *exact* t-distribution. In our setting the data are Bernoulli, so there is no exact t-distribution result. What justifies the z-test here is the **Normal approximation to the binomial**: by the CLT, the sample proportion $\\hat\\pi$ from a Bernoulli population converges to a Normal distribution as $n \\to \\infty$, and so does the difference $\\hat\\theta$.\n\nThere is a subtlety worth noting: we plug in $\\hat\\pi_A$ and $\\hat\\pi_B$ — estimated, not true — when computing the SE. In small samples, this additional estimation uncertainty means the test statistic is not quite standard Normal, and a t-distribution with finite degrees of freedom would be more appropriate. In large samples ($n \\gtrsim 30$ per group, and certainly at $n = 1000$), the t-distribution converges to the standard Normal, so the distinction disappears in practice. The key takeaway: the z-test is valid here because the Normal approximation to the binomial holds for large samples, not because we know the true variance.\n\n::: {#a90ae0b5 .cell execution_count=6}\n``` {.python .cell-code}\nz_stat = theta_hat / se_analytical\np_value = 2 * (1 - stats.norm.cdf(abs(z_stat)))\n\nprint(f\"Point estimate θ̂ = {theta_hat:.4f}\")\nprint(f\"Standard error    = {se_analytical:.4f}\")\nprint(f\"z-statistic       = {z_stat:.3f}\")\nprint(f\"p-value           = {p_value:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPoint estimate θ̂ = 0.0250\nStandard error    = 0.0183\nz-statistic       = 1.370\np-value           = 0.1708\n```\n:::\n:::\n\n\nWith a z-statistic of 1.370 and a p-value of 0.171, we **fail to reject** the null hypothesis at the conventional $\\alpha = 0.05$ level. The data do not provide statistically significant evidence that CTA A and CTA B differ in sign-up rate — at least not in this particular simulated sample. This is a useful reminder that even when a true effect exists ($\\theta = 0.04$), a single sample of 1,000 per group does not guarantee a significant result; sampling variability can obscure a real but modest difference.\n\n---\n\n## The T-Test as a Regression\n\nIt turns out the two-sample test we just ran is mathematically equivalent to a simple linear regression. This equivalence is worth understanding because regression software can serve as a drop-in replacement for the t-test, and the framework naturally extends to more complex designs.\n\n**Setup:** Stack the CTA A and CTA B outcomes into a single dataset. Each row has:\n\n- $Y_i$: 1 if visitor $i$ signed up, 0 otherwise\n- $D_i$: 1 if visitor $i$ saw CTA A, 0 if they saw CTA B\n\nWe then fit:\n$$Y_i = \\beta_0 + \\beta_1 D_i + \\varepsilon_i$$\n\nThe coefficients have natural interpretations:\n\n1. $\\beta_0 = E[Y_i \\mid D_i = 0]$ — the mean of the B group, estimating $\\pi_B$\n2. $\\beta_0 + \\beta_1 = E[Y_i \\mid D_i = 1]$ — the mean of the A group, estimating $\\pi_A$\n3. Therefore $\\beta_1 = \\pi_A - \\pi_B = \\theta$, and the OLS estimate $\\hat\\beta_1$ is numerically identical to $\\hat\\theta = \\bar{X}_A - \\bar{X}_B$\n\n::: {#be6cd3cd .cell execution_count=7}\n``` {.python .cell-code}\nY = np.concatenate([data_A, data_B])\nD = np.concatenate([np.ones(n), np.zeros(n)])\nX = sm.add_constant(D)\n\nmodel_ols  = sm.OLS(Y, X).fit()\nmodel_hc1  = sm.OLS(Y, X).fit(cov_type=\"HC1\")\nmodel_hc3  = sm.OLS(Y, X).fit(cov_type=\"HC3\")\n\ncomparison = pd.DataFrame({\n    \"SE type\":     [\"OLS (homoscedastic)\", \"HC1 robust\", \"HC3 robust\"],\n    \"β̂₁ estimate\": [model_ols.params[1]] * 3,\n    \"Std. Error\":  [model_ols.bse[1], model_hc1.bse[1], model_hc3.bse[1]],\n    \"t-statistic\": [model_ols.tvalues[1], model_hc1.tvalues[1], model_hc3.tvalues[1]],\n    \"p-value\":     [model_ols.pvalues[1], model_hc1.pvalues[1], model_hc3.pvalues[1]],\n}).round(4)\n\nprint(comparison.to_string(index=False))\nprint(f\"\\nTwo-sample reference: θ̂ = {theta_hat:.4f},  SE = {se_analytical:.4f},  z = {z_stat:.3f},  p = {p_value:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            SE type  β̂₁ estimate  Std. Error  t-statistic  p-value\nOLS (homoscedastic)         0.025      0.0183       1.3688   0.1712\n         HC1 robust         0.025      0.0183       1.3688   0.1710\n         HC3 robust         0.025      0.0183       1.3682   0.1713\n\nTwo-sample reference: θ̂ = 0.0250,  SE = 0.0183,  z = 1.370,  p = 0.1708\n```\n:::\n:::\n\n\nThe coefficient $\\hat\\beta_1$ matches our earlier $\\hat\\theta$ exactly across all three SE variants. A few things to note:\n\n**Homoscedastic vs. robust SEs.** Standard OLS assumes that the variance of $\\varepsilon_i$ is the same for all observations (homoscedasticity). In an A/B test with a binary outcome, this assumption is almost certainly violated: the variance of a Bernoulli random variable is $\\pi(1-\\pi)$, which differs between groups whenever $\\pi_A \\neq \\pi_B$. Using **HC1** or **HC3 heteroscedasticity-consistent standard errors** (White's robust SEs) corrects for this without requiring any assumption about the error structure.\n\n- **HC1** applies a degrees-of-freedom correction: $\\frac{n}{n-k}$ times the squared residuals.\n- **HC3** uses a leave-one-out adjustment that is more conservative and performs better in small samples.\n\nIn practice, for large balanced A/B tests the three approaches give nearly identical results — as we see here. But defaulting to robust SEs is a good habit: it costs nothing and insures against heteroscedasticity, clustering, or other violations that could otherwise produce misleadingly narrow confidence intervals.\n\n**A note on using OLS with a binary outcome.** This model — regressing a 0/1 outcome on a treatment indicator — is known as the **Linear Probability Model (LPM)**. A natural question is: why not use logistic regression, which is purpose-built for binary outcomes?\n\nThe answer is that in A/B testing, we care about the *treatment effect* $\\beta_1 = \\pi_A - \\pi_B$, not about predicting individual probabilities. The LPM gives us an unbiased, directly interpretable estimate of this difference. Logistic regression would model the log-odds ratio, which does not translate cleanly into a probability difference without additional computation.\n\nThe standard objection to LPM — that it can produce predicted probabilities outside $[0, 1]$ — matters for prediction tasks but is irrelevant here. With a binary treatment indicator, the model only ever predicts two values: $\\hat\\beta_0$ for the control group and $\\hat\\beta_0 + \\hat\\beta_1$ for the treatment group, both of which will be valid proportions as long as the sample sizes are reasonable. Using the LPM for causal inference in randomized experiments is standard practice in both industry and academic economics.\n\nThe regression framing also scales naturally: you can add covariates (device type, traffic source) to increase precision, interaction terms to detect heterogeneous treatment effects, or additional treatment arms — all within the same unified framework.\n\n---\n\n## Effect Size and Minimum Detectable Effect\n\nStatistical significance tells us whether an effect is *real*; it says nothing about whether the effect is *worth acting on*. In business settings — especially fintech or e-commerce — the more important question is often **economic significance**: is the measured difference large enough to justify the cost of change?\n\n### Effect size\n\nA natural way to standardize $\\hat\\theta$ is Cohen's $h$ for proportions:\n\n$$h = 2\\arcsin(\\sqrt{\\hat\\pi_A}) - 2\\arcsin(\\sqrt{\\hat\\pi_B})$$\n\nThe arcsine transformation stabilizes variance across different baseline rates, making $h$ comparable across experiments with different baseline conversion rates.\n\n::: {#2f76b1ed .cell execution_count=8}\n``` {.python .cell-code}\nh = 2 * np.arcsin(np.sqrt(pi_hat_A)) - 2 * np.arcsin(np.sqrt(pi_hat_B))\nprint(f\"Estimated effect size (Cohen's h) = {h:.4f}\")\nprint(f\"Interpretation: {'small' if abs(h) < 0.2 else 'medium' if abs(h) < 0.5 else 'large'} effect (Cohen's benchmarks: 0.2 / 0.5 / 0.8)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated effect size (Cohen's h) = 0.0612\nInterpretation: small effect (Cohen's benchmarks: 0.2 / 0.5 / 0.8)\n```\n:::\n:::\n\n\nOur effect is small by conventional benchmarks — a useful reminder that statistical significance and practical importance are not the same thing.\n\n### Minimum Detectable Effect (MDE)\n\nBefore running an experiment, a product team must decide: *what is the smallest effect we actually care about detecting?* This is the **Minimum Detectable Effect (MDE)**. Given a chosen MDE, desired power $1-\\beta$, and significance level $\\alpha$, the required sample size per group is:\n\n$$n = \\frac{(z_{1-\\alpha/2} + z_{1-\\beta})^2 \\cdot [\\hat\\pi_A(1-\\hat\\pi_A) + \\hat\\pi_B(1-\\hat\\pi_B)]}{\\text{MDE}^2}$$\n\n::: {#05d76455 .cell execution_count=9}\n``` {.python .cell-code}\nalpha = 0.05\npower = 0.80\nz_alpha = stats.norm.ppf(1 - alpha / 2)   # 1.96\nz_beta  = stats.norm.ppf(power)            # 0.84\n\nmde_values = np.array([0.01, 0.02, 0.03, 0.04, 0.05, 0.10])\nbaseline   = 0.20   # assumed shared baseline sign-up rate\n\nrequired_n = (z_alpha + z_beta)**2 * 2 * baseline * (1 - baseline) / mde_values**2\n\nmde_table = pd.DataFrame({\n    \"MDE (pp)\":         [f\"{m*100:.0f}%\" for m in mde_values],\n    \"Required n / group\": required_n.astype(int),\n    \"Total visitors\":   (required_n * 2).astype(int),\n})\nprint(mde_table.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMDE (pp)  Required n / group  Total visitors\n      1%               25116           50232\n      2%                6279           12558\n      3%                2790            5581\n      4%                1569            3139\n      5%                1004            2009\n     10%                 251             502\n```\n:::\n:::\n\n\nThe table shows the steep cost of chasing small effects. To reliably detect a 1 percentage-point lift you need tens of thousands of visitors per group; a 4 pp lift (our simulated truth) requires a few hundred. In practice, the MDE should be set by the *business*, not the statistician: if a 1 pp improvement in sign-up rate translates to \\$50k/year in additional revenue but the engineering change costs \\$200k to maintain, the experiment is not worth running regardless of statistical power.\n\n**The right question is not \"is the effect significant?\" but \"is the effect large enough to matter — and is running this experiment worth the cost?\"**\n\n---\n\n## The Problem with Peeking\n\nSuppose my boss is impatient. Rather than waiting until all 1,000 visitors have been observed in each group, she wants to check the results after every 100 visitors per group (at $n = 100, 200, \\ldots, 1000$) — and declare a winner as soon as any of those 10 tests comes back significant at $\\alpha = 0.05$.\n\nThis practice is known as **peeking**, and it is a serious problem in classical frequentist testing.\n\nA single test at $\\alpha = 0.05$ has a 5% false positive rate: it will incorrectly reject a true null hypothesis 5% of the time. But each additional peek gives another opportunity for a spurious significant result. Across 10 peeks on accumulating data, the overall probability of at least one false rejection is much higher than 5% — even when there is truly no difference.\n\nTo quantify this, I simulate 10,000 experiments in a world where **the null is true**: $\\pi_A = \\pi_B = 0.20$, so $\\theta = 0$. In each experiment, I peek at 10 equally spaced checkpoints and record whether *any* peek yields $p < 0.05$.\n\n::: {#5dade48f .cell execution_count=10}\n``` {.python .cell-code}\npi_null = 0.20\ncheckpoints = np.arange(100, 1001, 100)\nn_experiments = 10_000\nfalse_positives = 0\n\nfor _ in range(n_experiments):\n    sim_A = rng.binomial(1, pi_null, n)\n    sim_B = rng.binomial(1, pi_null, n)\n\n    flagged = False\n    for cp in checkpoints:\n        a_sub = sim_A[:cp]\n        b_sub = sim_B[:cp]\n        p_hat_a = a_sub.mean()\n        p_hat_b = b_sub.mean()\n        diff = p_hat_a - p_hat_b\n        se = np.sqrt(p_hat_a * (1 - p_hat_a) / cp + p_hat_b * (1 - p_hat_b) / cp)\n        if se > 0:\n            z = diff / se\n            p = 2 * (1 - stats.norm.cdf(abs(z)))\n            if p < 0.05:\n                flagged = True\n                break\n\n    if flagged:\n        false_positives += 1\n\nempirical_fpr = false_positives / n_experiments\n\nprint(f\"Nominal false positive rate (single test): 5.00%\")\nprint(f\"Empirical false positive rate (10 peeks):  {empirical_fpr * 100:.1f}%\")\nprint(f\"Inflation factor: {empirical_fpr / 0.05:.1f}x\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNominal false positive rate (single test): 5.00%\nEmpirical false positive rate (10 peeks):  19.4%\nInflation factor: 3.9x\n```\n:::\n:::\n\n\nThe empirical false positive rate under peeking is roughly **2–3× the nominal 5% level**. That means if your boss follows this strategy in a world where neither CTA is actually better, she will incorrectly declare a winner in roughly 1 out of every 5–6 experiments — not 1 in 20 as intended.\n\n### What can we do about it?\n\nThe root cause is that multiple correlated tests on accumulating data compound the chance of a spurious signal. Several approaches exist, each with different trade-offs:\n\n| Approach | Idea | Trade-off |\n|---|---|---|\n| **Pre-register & test once** | Fix $n$ in advance, test at the end only | Simple, but no early stopping |\n| **Bonferroni correction** | Divide $\\alpha$ by the number of peeks ($\\alpha' = 0.05/10 = 0.005$) | Conservative; loses power |\n| **Sequential testing (mSPRT)** | Use a mixture Sequential Probability Ratio Test — designed so you can peek at any time and the Type I error stays controlled | Used by Optimizely, Netflix; requires choosing a prior on effect size |\n| **Group Sequential Methods** | Pre-specify a small number of interim analyses with adjusted thresholds (e.g., O'Brien-Fleming) | Common in clinical trials; less flexible than mSPRT |\n\nIn industry, **mSPRT** (mixture Sequential Probability Ratio Test) has become the standard for online experimentation platforms. It produces *always-valid p-values*: you can check the result at any point during the experiment and the false positive rate is still controlled at $\\alpha$. The key insight is that the test statistic is a likelihood ratio martingale, which by construction satisfies a valid stopping rule at any time.\n\n**Bottom line:** Classical p-values carry a one-shot guarantee. If you need to monitor an experiment in real time, use a method built for sequential testing — don't apply a fixed-horizon test to interim data.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}